# -*- coding: utf-8 -*-
"""Vectors in Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uzYKax1ELVutrnR1LivbCtZN2x5u_82K
"""

import numpy  as np
v1=np.array([999, 666, 333])
v2=np.array([1,333, 6666])

print(v1+v2)

print(v1-v2)



print(3*v1)

print(np.linalg.norm(v1))

print(np.dot(v1,v2))

